/*
 * Timer1_Config.h
 *
 * Created: 2024/09/17 5:40:06 PM
 *  Author: Karim Mohamed
 */ 


#ifndef TIMER1_CONFIG_H_
#define TIMER1_CONFIG_H_

/*
 * choose from:
 *   TIMER1_PRESCALER_1
 *   TIMER1_PRESCALER_8
 *   TIMER1_PRESCALER_64
 *   TIMER1_PRESCALER_256
 *   TIMER1_PRESCALER_1024
 *   TIMER1_PRESCALER_EXTCLK_FALLEDGE
 *   TIMER1_PRESCALER_EXTCLK_RAISEDGE
 */
#define TIMER1_PRESCALER	TIMER1_PRESCALER_8
/*
 *   choose from :
 *   TIMER1_NORMAL_MODE
 *   TIMER1_FASTPWM_ICR_MODE
 *   TIMER1_FASTPWM_COMPAREMATCH_MODE
 *
 */
#define TIMER1_MODE  TIMER1_FASTPWM_COMPAREMATCH_MODE

/*
 * choose from :
 *  Non PWM:
 *   TIMER1_OC1_DISCONNECTED
 *   TIMER1_OC1_TOG
 *   TIMER1_OC1_CLEAR
 *   TIMER1_OC1_SET
 *   TIMER1_OC1_PWM_NON_INVERTING
 *   TIMER1_OC1_PWM_INVERTING
 */
#define TIMER1_OC1_MODE  TIMER1_OC1_PWM_NON_INVERTING

#endif /* TIMER1_CONFIG_H_ */